# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  if ENV["FILES"]
    fileList = ENV["FILES"].split
    t.test_files =  ENV["FILES"].split(',')
  else
    t.test_files = FileList["test/*_test.rb"]
  end
  t.options = '--junit --junit-filename=tmp/junit.xml'
end